### ISSUE TITLE
linux-installer.pl find syntax error.

### ISSUE THREAD

**Issue by Thanosgrc** [dobey/diogenes-ng#1]
With a fresh and updated Ubuntu-Mate 18.04.1 LTS VM after installing perl packages:

> 
> root@test:/home/test/Downloads/diogenes-ng-0.3.2.0# ./linux-installer.pl 
> 
> 
> _Going to install Diogenes in /usr/local/diogenes-ng and /usr/local/bin.
> Supply your password (for sudo) if prompted.
> 
> Ctrl-c to cancel, Enter to continue.
> 
> find: missing argument to `-exec'
> Died at ./linux-installer.pl line 26, <> line 1._

**Comment by dobey** [comment]
I've fixed this and created an 0.3.2.0.1 release. Hopefully this should work for you now.
