### ISSUE TITLE
Some more errors

### ISSUE THREAD

**Issue by Thanosgrc** [dobey/diogenes-ng#2]
test@test:~$ sudo diogenes-ng 

> 
> /usr/local/bin/diogenes-ng: 21: /usr/local/bin/diogenes-ng: function: not found
> Could not find user profile dir! 
> Use of uninitialized value in subroutine entry at /usr/local/diogenes-ng/perl/diogenes-server-kill.pl line 12.
> Running diogenes-server-kill.pl
> diogenes-server-kill.pl exiting.
> /usr/local/bin/diogenes-ng: 23: /usr/local/bin/diogenes-ng: Syntax error: "}" unexpected

**Comment by dobey** [comment]
You should not run the app with sudo or as root. Only the install script needs to be run with root permissions. I've resolved these issues. Please try https://github.com/dobey/diogenes-ng/releases/tag/0.3.2.0.2 now.

Thank you for your patience.
